/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import Service.HospitalService;
import Service.MedicalRequest;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 *  
 */
public class HospitalAdmin extends javax.swing.JFrame {

    /**
     * Creates new form HospitalAdmin
     */
    public static String unallocatedTableName = "unallocatedHospitalRequests";
    public static String counsellingTableName = "counsellingRequests";
    public static String testsTableName = "testsRequests";
    public String Memail;
    public String Mpass;
//    public HospitalAdmin() {
//        initComponents();
//    }
//
//    HospitalAdmin(String email) {
//      // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
//    }

    HospitalAdmin(String email, String password) {
        this.Memail = email;
        this.Mpass = password;
       initComponents();
        // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCloseAdmin = new javax.swing.JLabel();
        lblCreateTitle = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDetails = new javax.swing.JTable();
        btnReject = new javax.swing.JButton();
        btnTestDept = new javax.swing.JButton();
        btnCounDept = new javax.swing.JButton();
        TFAssDept = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TFReqId = new javax.swing.JTextField();
        btnUnalllocated = new javax.swing.JButton();
        btnAccept = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblAdminLogout = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1550, 820));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(956, 570));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCloseAdmin.setBackground(new java.awt.Color(68, 168, 217));
        lblCloseAdmin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblCloseAdmin.setForeground(new java.awt.Color(255, 255, 255));
        lblCloseAdmin.setText("X");
        lblCloseAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseAdminMouseClicked(evt);
            }
        });
        getContentPane().add(lblCloseAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1510, 0, 20, 30));

        lblCreateTitle.setBackground(new java.awt.Color(68, 168, 217));
        lblCreateTitle.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblCreateTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblCreateTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCreateTitle.setText("Hospital Manager Portal ");
        lblCreateTitle.setOpaque(true);
        getContentPane().add(lblCreateTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1550, 60));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jScrollPane1.setColumnHeaderView(null);
        jScrollPane1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        tblDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Request_Id", "Victim_Email", "Case_Desc", "Assigned_To", "Status", "Notes"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDetailsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDetails);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 820, 300));

        btnReject.setBackground(new java.awt.Color(255, 153, 51));
        btnReject.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnReject.setText("Reject");
        btnReject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRejectActionPerformed(evt);
            }
        });
        jPanel1.add(btnReject, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 700, 190, 40));

        btnTestDept.setBackground(new java.awt.Color(255, 153, 51));
        btnTestDept.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnTestDept.setText("Testing Dept Requests");
        btnTestDept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTestDeptActionPerformed(evt);
            }
        });
        jPanel1.add(btnTestDept, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 230, 50));

        btnCounDept.setBackground(new java.awt.Color(255, 153, 51));
        btnCounDept.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCounDept.setText("Counseling Dept Requests");
        btnCounDept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCounDeptActionPerformed(evt);
            }
        });
        jPanel1.add(btnCounDept, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 90, 230, 50));

        TFAssDept.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(TFAssDept, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 620, 310, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Assigning Department:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 610, 180, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Request Id:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 530, 180, 50));

        TFReqId.setEditable(false);
        TFReqId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(TFReqId, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 540, 310, 40));

        btnUnalllocated.setBackground(new java.awt.Color(255, 153, 51));
        btnUnalllocated.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUnalllocated.setText("Unallocated Request ");
        btnUnalllocated.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnalllocatedActionPerformed(evt);
            }
        });
        jPanel1.add(btnUnalllocated, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 230, 50));

        btnAccept.setBackground(new java.awt.Color(255, 153, 51));
        btnAccept.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAccept.setText("Accept and Allocate  ");
        btnAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptActionPerformed(evt);
            }
        });
        jPanel1.add(btnAccept, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 700, 190, 40));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/hospital4.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 90, 520, -1));

        lblAdminLogout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblAdminLogout.setForeground(new java.awt.Color(0, 51, 102));
        lblAdminLogout.setText("Logout");
        lblAdminLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAdminLogoutMouseClicked(evt);
            }
        });
        jPanel1.add(lblAdminLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1470, 60, 70, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1550, 810));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptActionPerformed

        HospitalService hospitalService = new HospitalService();
        
        DefaultTableModel model = (DefaultTableModel) tblDetails.getModel();
        int selectedRowIndex = tblDetails.getSelectedRow();
        
        if(selectedRowIndex < 0 ){
            JOptionPane.showMessageDialog(this, "Please select a row to view");
            return;
        }
        
        String requestId = String.valueOf(model.getValueAt(selectedRowIndex, 0));
        String department = String.valueOf(TFAssDept.getText());
        
        if(department.equalsIgnoreCase("COUNSELLING DEPARTMENT"))
        {
            Boolean reponse = hospitalService.assignRequestToCounsellingDepartment(requestId);
            if(reponse != null)
                JOptionPane.showMessageDialog(this, "Successfully Assigned to Counselling Department !");
            populateTable(unallocatedTableName);
            TFReqId.setEditable(true);
            TFReqId.setText("");
            TFReqId.setEditable(false);
            TFAssDept.setText("");
            return;
        }
        if(department.equalsIgnoreCase("TEST DEPARTMENT"))
        {
            Boolean reponse = hospitalService.assignRequestToTestDepartment(requestId);
            if(reponse != null)
                JOptionPane.showMessageDialog(this, "Successfully Assigned to Testing Department !");
            TFReqId.setEditable(true);
            TFReqId.setText("");
            TFReqId.setEditable(false);
            TFAssDept.setText("");
            populateTable(unallocatedTableName);
            return;
        }
        JOptionPane.showMessageDialog(this, "Invalid Department !");
        return;
    }//GEN-LAST:event_btnAcceptActionPerformed

    private void btnUnalllocatedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnalllocatedActionPerformed
        populateTable(unallocatedTableName);
                jLabel2.setVisible(true);
        TFReqId.setVisible(true);
        jLabel1.setVisible(true);
        TFAssDept.setVisible(true);
        btnAccept.setVisible(true);
        btnReject.setVisible(true);
    }//GEN-LAST:event_btnUnalllocatedActionPerformed

    private void btnTestDeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTestDeptActionPerformed
        populateTable(testsTableName);
        jLabel2.setVisible(false);
        TFReqId.setVisible(false);
        jLabel1.setVisible(false);
        TFAssDept.setVisible(false);
        btnAccept.setVisible(false);
        btnReject.setVisible(false);
    }//GEN-LAST:event_btnTestDeptActionPerformed

    private void btnCounDeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCounDeptActionPerformed
        populateTable(counsellingTableName);
                jLabel2.setVisible(false);
        TFReqId.setVisible(false);
        jLabel1.setVisible(false);
        TFAssDept.setVisible(false);
        btnAccept.setVisible(false);
        btnReject.setVisible(false);
    }//GEN-LAST:event_btnCounDeptActionPerformed

    private void btnRejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejectActionPerformed

        //enter comments to reject
        String c = JOptionPane.showInputDialog(this, "Enter Reason for Rejection");
        
        HospitalService hospitalService = new HospitalService();
        
        DefaultTableModel model = (DefaultTableModel) tblDetails.getModel();
        int selectedRowIndex = tblDetails.getSelectedRow();
        
        if(selectedRowIndex < 0 ){
            JOptionPane.showMessageDialog(this, "Please select a row to view");
            return;
        }
        
        int i = JOptionPane.showConfirmDialog(null, "Are you sure you want to Reject this case?");
        // 0=yes, 1=no, 2=cancel
        System.out.println(i);
        
        if(i==0)
        {
            String requestId = String.valueOf(model.getValueAt(selectedRowIndex, 0));
            Boolean r = hospitalService.rejectCase(requestId, c);
            if(r)
                JOptionPane.showMessageDialog(null, "Successfully rejected case");
            populateTable(unallocatedTableName);
        }
        return;
    }//GEN-LAST:event_btnRejectActionPerformed

    private void tblDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDetailsMouseClicked
        DefaultTableModel model = (DefaultTableModel) tblDetails.getModel();
        int selectedRowIndex = tblDetails.getSelectedRow();
        
        if(selectedRowIndex < 0 ){
            JOptionPane.showMessageDialog(this, "Please select a row to view");
            return;
        }
        String requestId = String.valueOf(model.getValueAt(selectedRowIndex, 0));
        TFReqId.setText(requestId);
        
    }//GEN-LAST:event_tblDetailsMouseClicked

    private void lblCloseAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseAdminMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new HomePage().setVisible(true);
    }//GEN-LAST:event_lblCloseAdminMouseClicked

    private void lblAdminLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAdminLogoutMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Successfully Logout");
        this.dispose();
        new HomePage().setVisible(true);
    }//GEN-LAST:event_lblAdminLogoutMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(HospitalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(HospitalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(HospitalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(HospitalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new HospitalAdmin().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TFAssDept;
    private javax.swing.JTextField TFReqId;
    private javax.swing.JButton btnAccept;
    private javax.swing.JButton btnCounDept;
    private javax.swing.JButton btnReject;
    private javax.swing.JButton btnTestDept;
    private javax.swing.JButton btnUnalllocated;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAdminLogout;
    private javax.swing.JLabel lblCloseAdmin;
    private javax.swing.JLabel lblCreateTitle;
    private javax.swing.JTable tblDetails;
    // End of variables declaration//GEN-END:variables

    private void populateTable(String tableName) {
        
        DefaultTableModel model = (DefaultTableModel) tblDetails.getModel();
        model.setRowCount(0);
        
        HospitalService hospitalService = new HospitalService();
        ArrayList<MedicalRequest> result = new ArrayList<>();
        if(tableName.equals(unallocatedTableName))
        {
            result = hospitalService.getAllUnallocatedMedicalRequests();
        }
        if(tableName.equals(counsellingTableName))
        {
            result = hospitalService.getCounsellingMedicalRequests("");
        }
        if(tableName.equals(testsTableName))
        {
            result = hospitalService.getTestMedicalRequests("");
        }
        if(result == null)
        {
            JOptionPane.showMessageDialog(null, "No Data Available");
            return;
        }
        
        for(MedicalRequest r: result)
        {
            Object[] row = new Object[11];
            row[0] = r.getRequest_Id();
            row[1] = r.getVictim_email();
            row[2] = r.getProblem_Description();
            row[3]=r.getAssigned_To();
            row[4]=r.getStatus();
            //row[3] = r.getCaseDescription();
            //row[4] = r.getContact();
            row[5] = r.getNotes();
            model.addRow(row);
        }
    }
}
